"""add related_ride_id to notifications

Revision ID: 724d901b25d2
Revises: db5a908ddc1b
Create Date: 2026-10-04 15:41:21.429167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '724d901b25d2'
down_revision: Union[str, None] = 'db5a908ddc1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('related_ride_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'notifications_related_ride_id_fkey',
        'notifications', 'ride_requests', ['related_ride_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notifications_related_ride_id_fkey', 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'related_ride_id')
    # ### end Alembic commands ###
