"""initial schema

Revision ID: db5a908ddc1b
Revises: 
Create Date: 2026-10-01 13:51:15.004071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'db5a908ddc1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('ride_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pickup_address', sa.String(), nullable=False),
    sa.Column('pickup_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('destination_address', sa.String(), nullable=False),
    sa.Column('destination_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('time_flexibility_minutes', sa.Integer(), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MATCH_PENDING', 'MATCHED', 'CANCELLED', 'EXPIRED', 'COMPLETED', name='ride_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ride_requests_destination_point', 'ride_requests', ['destination_point'], unique=False, postgresql_using='gist')
    op.create_index('idx_ride_requests_pickup_point', 'ride_requests', ['pickup_point'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_ride_requests_status'), 'ride_requests', ['status'], unique=False)
    op.create_index(op.f('ix_ride_requests_user_id'), 'ride_requests', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gender_preference', sa.Enum('NO_PREFERENCE', 'PREFER_SAME_GENDER', 'REQUIRE_SAME_GENDER', name='gender_preference'), nullable=False),
    sa.Column('default_time_window_minutes', sa.Integer(), nullable=False),
    sa.Column('default_pickup_radius_meters', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_a_id', sa.UUID(), nullable=False),
    sa.Column('request_b_id', sa.UUID(), nullable=False),
    sa.Column('destination_score', sa.Float(), nullable=False),
    sa.Column('time_score', sa.Float(), nullable=False),
    sa.Column('pickup_score', sa.Float(), nullable=False),
    sa.Column('preference_score', sa.Float(), nullable=False),
    sa.Column('route_overlap_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('SUGGESTED', 'A_ACCEPTED', 'B_ACCEPTED', 'CONFIRMED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='match_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_a_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_b_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_request_a_id'), 'matches', ['request_a_id'], unique=False)
    op.create_index(op.f('ix_matches_request_b_id'), 'matches', ['request_b_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_request_id', sa.UUID(), nullable=False),
    sa.Column('route_geometry', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_request_id')
    )
    op.create_index('idx_routes_route_geometry', 'routes', ['route_geometry'], unique=False, postgresql_using='gist')
    op.create_table('match_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_feedback_match_id'), 'match_feedback', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_feedback_match_id'), table_name='match_feedback')
    op.drop_table('match_feedback')
    op.drop_index('idx_routes_route_geometry', table_name='routes', postgresql_using='gist')
    op.drop_table('routes')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_request_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_request_a_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_ride_requests_user_id'), table_name='ride_requests')
    op.drop_index(op.f('ix_ride_requests_status'), table_name='ride_requests')
    op.drop_index('idx_ride_requests_pickup_point', table_name='ride_requests', postgresql_using='gist')
    op.drop_index('idx_ride_requests_destination_point', table_name='ride_requests', postgresql_using='gist')
    op.drop_table('ride_requests')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    sa.Enum(name='gender_preference').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='match_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ride_status').drop(op.get_bind(), checkfirst=True)
